TEMPLATE	= app
LANGUAGE	= C++

INCLUDEPATH	+= .

HEADERS	+= form1.ui.h

SOURCES	+= main.cpp

FORMS	= form1.ui

######################################################################
# Automatically generated by qmake (1.07a) Thu Aug 9 16:50:33 2012
######################################################################


# Input
