######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 7 20:09:42 2015
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form1.ui.h
INTERFACES += form1.ui
SOURCES += main.cpp
